# Generated by Django 4.2.20 on 2025-03-22 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='lieric', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and @/./+/-/_ characters.', regex='^[\\w.@+-]+$')]),
            preserve_default=False,
        ),
    ]
